name: Save Turborepo cache

inputs:
  turbo-repo-restore-action-id:
    description: Restore Turborepo cache action id
    required: true

runs:
  using: composite
  steps:
    - name: Save Turborepo cache
      id: cache-turborepo-save
      if: always() && steps.${{ inputs.turbo-repo-restore-action-id }}.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.${{ inputs.turbo-repo-restore-action-id }}.outputs.cache-primary-key }}
        path: .turbo
