name: CI

# PNPM setup based on https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            node-version: "22.8.0"
            cache: pnpm
            cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Turborepo cache
        id: cache-turborepo-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-turborepo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turborepo-
          path: .turbo

      - name: Build packages
        run: pnpm ci-build

      - name: Build basic sample
        run: pnpm ci-build-basic

      - name: Build endpoints sample
        run: pnpm ci-build-endpoints

      - name: Build basic webpack sample
        run: pnpm ci-build-basic-webpack

      - name: Lint packages & samples
        run: pnpm lint

      - name: Test packages
        run: pnpm test

      - name: Save Turborepo cache
        id: cache-turborepo-save
        if: always() && steps.cache-turborepo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-turborepo-restore.outputs.cache-primary-key }}
          path: .turbo
