name: CI

# PNPM setup based on https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/composite-actions/setup
        with:
          turbo-repo-restore-action-id: cache-turborepo-restore

      - name: Lint packages & samples
        run: pnpm lint

      - name: Build packages
        run: pnpm build-pkg

      - name: Build basic sample
        run: pnpm build-basic

      - name: Build basic webpack sample
        run: pnpm build-basic-webpack

      - name: Build basic mix sample
        run: pnpm build-basic-mix

      - name: Build endpoints sample
        run: pnpm build-endpoints

      - name: Test packages
        run: pnpm test

      - name: Setup
        uses: ./.github/composite-actions/save-turbo-cache
        with:
          turbo-repo-restore-action-id: cache-turborepo-restore

    #   - name: Save Turborepo cache
    #     id: cache-turborepo-save
    #     if: always() && steps.cache-turborepo-restore.outputs.cache-hit != 'true'
    #     uses: actions/cache/save@v4
    #     with:
    #       key: ${{ steps.cache-turborepo-restore.outputs.cache-primary-key }}
    #       path: .turbo
